#!/bin/sh
set -e

# configure php additions.ini
cat /etc/php.d/05-additions.ini.template \
  | envsubst '${MAILHOG_HOST} ${MAILHOG_PORT}' \
  | sudo tee /etc/php.d/05-additions.ini

# append warden issued root ca cert to ca-bundle trusted by curl/openssl
if [ -f /etc/ssl/warden-rootca-cert/ca.cert.pem ]; then
  sudo cp /etc/ssl/warden-rootca-cert/ca.cert.pem /etc/pki/ca-trust/source/anchors/warden-rootca-cert.pem
fi

# update trust outside if condition above to allow mounting PEM files into /etc/pki/ca-trust/source/anchors
sudo update-ca-trust

# start socat process in background to connect sockets used for agent access within container environment
if [[ -S /run/host-services/ssh-auth.sock ]] \
  && [[ "${SSH_AUTH_SOCK}" != "/run/host-services/ssh-auth.sock" ]]
then
  sudo bash -c "nohup socat UNIX-CLIENT:/run/host-services/ssh-auth.sock \
    UNIX-LISTEN:${SSH_AUTH_SOCK},fork,user=www-data,group=www-data 1>/var/log/socat-ssh-auth.log 2>&1 &"
fi

# install requested node version if not already installed
NODE_INSTALLED="$(node -v | perl -pe 's/^v([0-9]+)\..*$/$1/')";
if [ "${NODE_INSTALLED}" != "${NODE_VERSION}" ] \
  || [ "${NODE_VERSION}" = "latest" ] || [ "${NODE_VERSION}" = "lts" ]
then
  sudo n "${NODE_VERSION}"
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- php-fpm "$@"
fi

exec "$@"
