#!/bin/sh
set -e

# configure php additions.ini
envsubst '${MAILHOG_HOST} ${MAILHOG_PORT}' \
	< /etc/php.d/05-additions.ini.template > /etc/php.d/05-additions.ini

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
