version: "3.5"
services:
  nginx:
    hostname: "${WARDEN_ENV_NAME}-nginx"
    image: quay.io/warden/nginx:${NGINX_VERSION:-1.16}
    environment:
      - NGINX_TEMPLATE=laravel.conf
      - NGINX_PUBLIC=/public
    depends_on:
      - php-fpm
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=1
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-nginx.loadbalancer.server.port=80
    networks:
      - warden
      - default

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    image: quay.io/warden/php-fpm:${PHP_VERSION:-7.2}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - NODE_VERSION=${NODE_VERSION:-10}
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    networks:
      - default
      - warden

  php-debug:
    hostname: "${WARDEN_ENV_NAME}-php-debug"
    image: quay.io/warden/php-fpm:${PHP_VERSION:-7.2}-debug
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - NODE_VERSION=${NODE_VERSION:-10}
      - PHP_IDE_CONFIG=serverName=${WARDEN_ENV_NAME}-docker
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    networks:
      - default
      - warden

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: quay.io/warden/mariadb:${MARIADB_VERSION:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-laravel}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laravel}
      - MYSQL_USER=${MYSQL_USER:-laravel}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - warden
      - default

  redis:
    hostname: "${WARDEN_ENV_NAME}-redis"
    image: quay.io/warden/redis:${REDIS_VERSION:-5.0}

  mailhog:
    hostname: "${WARDEN_ENV_NAME}-mailhog"
    image: quay.io/warden/mailhog:${MAILHOG_VERSION:-1.0}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mailhog.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mailhog.rule=Host(`mailhog.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-mailhog.loadbalancer.server.port=8025
    networks:
      - warden
      - default

volumes:
  dbdata:

networks:
  warden:
    external: true
