version: "3.5"
services:
  nginx:
    hostname: "${WARDEN_ENV_NAME}-nginx"
    image: davidalger/warden:nginx-${NGINX_VERSION:-1.16}-alpine
    environment:
      - NGINX_TEMPLATE=magento1.conf
    depends_on:
      - php-fpm
    volumes:
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.priority=1
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-nginx.loadbalancer.server.port=80
    networks:
      - warden
      - default

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    image: davidalger/warden:mage1-fpm-${PHP_VERSION:-7.2}
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - NODE_VERSION=${NODE_VERSION:-10}
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    networks:
      - default
      - warden

  php-debug:
    hostname: "${WARDEN_ENV_NAME}-php-debug"
    image: davidalger/warden:mage1-fpm-${PHP_VERSION:-7.2}-debug
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - NODE_VERSION=${NODE_VERSION:-10}
      - PHP_IDE_CONFIG=serverName=${WARDEN_ENV_NAME}-docker
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    networks:
      - default
      - warden

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: mariadb:${MARIADB_VERSION:-10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}
    command:
      - mysqld
      - --max_allowed_packet=1024M
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - warden
      - default

  redis:
    hostname: "${WARDEN_ENV_NAME}-redis"
    image: redis:${REDIS_VERSION:-5.0}-alpine

  mailhog:
    hostname: "${WARDEN_ENV_NAME}-mailhog"
    image: mailhog/mailhog:${MAILHOG_VERSION:-v1.0.0}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mailhog.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-mailhog.rule=Host(`mailhog.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-mailhog.loadbalancer.server.port=8025
    networks:
      - warden
      - default

volumes:
  dbdata:

networks:
  warden:
    external: true
