version: "3.5"
services:
  php-blackfire:
    hostname: "${WARDEN_ENV_NAME}-php-blackfire"
    image: quay.io/warden/php-fpm:${PHP_VERSION:-7.2}-magento1-blackfire
    depends_on:
      - db
    volumes:
      - ~/.warden/ssl/rootca/certs:/etc/ssl/warden-rootca-cert:ro
      - ~/.composer:/home/www-data/.composer:delegated
      - .${WARDEN_WEB_ROOT:-}/:/var/www/html:delegated
    networks:
      - warden
      - default

  blackfire-agent:
    hostname: "${WARDEN_ENV_NAME}-blackfire-agent"
    image: blackfire/blackfire:latest
    environment:
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
    networks:
      - warden
      - default
