name: Installing or Upgrading through Homebrew
description: Report an issue with the Warden software when installing or upgrading through Homebrew
title: '[Brew] '
labels: bug, brew update
type: bug
projects: wardenenv/1
body:
  - type: input
    id: version
    attributes:
      label: Version of Homebrew
      description: Run `brew -v` and provide the output
      placeholder: brew -v
    validations:
      required: true
  - type: input
    id: install
    attributes:
      label: Operating System and Installation Method
      description: Please tell us which operating system you're running brew on. (E.g. "Mac OS 12.6")
      placeholder: Mac OS 12.6
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'  
        2. Click on '....'  
        3. Scroll down to '....'  
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen and when
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
