version: "3.5"
services:
  magepack:
    hostname: "${WARDEN_ENV_NAME}-magepack"
    image: ghcr.io/drpayyne/warden-magepack
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
    extra_hosts:
      - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - php-fpm
