#!/bin/sh
set -e

# configure mailhog
envsubst '${MAILHOG_HOST} ${MAILHOG_PORT}' \
	< /usr/local/etc/php/conf.d/10-additions.ini.template > /usr/local/etc/php/conf.d/10-additions.ini

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
