services:
  opensearch:
    hostname: "${WARDEN_ENV_NAME}-opensearch"
    image: ${WARDEN_IMAGE_REPOSITORY}/opensearch:${OPENSEARCH_VERSION:-1.2}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-opensearch.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-opensearch.rule=Host(`opensearch.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-opensearch.loadbalancer.server.port=9200
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
    environment:
      - DISABLE_SECURITY_PLUGIN=true
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms64m -Xmx512m"
    volumes:
      - osdata:/usr/share/opensearch/data

volumes:
  osdata:
