services:
  rabbitmq:
    hostname: "${WARDEN_ENV_NAME}-rabbitmq"
    image: ${WARDEN_IMAGE_REPOSITORY}/rabbitmq:${RABBITMQ_VERSION:-3.8}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-rabbitmq.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-rabbitmq.rule=Host(`rabbitmq.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-rabbitmq.loadbalancer.server.port=15672
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
      - sablier.enable=true
      - sablier.group=${WARDEN_ENV_NAME}
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
