name: Docker Image Mailhog
on:
  schedule:
  - cron: "0 6 * * 1"   # 6 AM UTC on Monday
  push:
    paths:
    - version
    - images/mailhog/**
    branches:
    - develop
jobs:
  mailhog:
    name: Mailhog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: mailhog
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
